version: '3.8'

services:
  fanatgrust:
    build: .
    image: fanallmrust
    container_name: ${CONTAINER_NAME}
    environment:
      - RUST_LOG=info
      - RUST_BACKTRACE=1
      - API_KEY=${API_KEY} 
      - GROQ_API_KEY=${GROQ_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY} 
    ports:
      - "6004:6004"
    volumes:
      - ./logs:/usr/src/app/logs
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 2G
    restart: always

